# Generated by Django 4.0.3 on 2022-04-02 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_fr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=255, verbose_name='Назва категорії')),
                ('slug_fr', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категорія(ю)',
                'verbose_name_plural': 'Категорії',
                'ordering': ['title_fr'],
            },
        ),
        migrations.CreateModel(
            name='Contact_fr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('author_fr', models.CharField(blank=True, max_length=150, verbose_name='Автор')),
                ('content_fr', models.TextField(blank=True, verbose_name='Вміст')),
                ('created_at_fr', models.DateTimeField(auto_now_add=True, verbose_name='Створено коли')),
            ],
            options={
                'verbose_name': 'Форма(у) контакту',
                'verbose_name_plural': 'Форми контакту',
                'ordering': ['-created_at_fr'],
            },
        ),
        migrations.CreateModel(
            name='Tag_fr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=255, verbose_name='Назва тєгу')),
                ('slug_fr', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Тег(у)',
                'verbose_name_plural': 'Теги',
                'ordering': ['title_fr'],
            },
        ),
        migrations.CreateModel(
            name='Post_fr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=255, verbose_name='Заголовок публікації')),
                ('slug_fr', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('author_fr', models.CharField(blank=True, max_length=150, verbose_name='Автор')),
                ('content_fr', models.TextField(blank=True, verbose_name='Вміст')),
                ('photo_fr', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('created_at_fr', models.DateTimeField(auto_now_add=True, verbose_name='Створено коли')),
                ('published_fr', models.BooleanField(default=True, verbose_name='Опублікувати')),
                ('views_fr', models.IntegerField(default=0, verbose_name='Кількість переглядів')),
                ('short_story_fr', models.BooleanField(default=False, verbose_name='Коротка новина')),
                ('category_fr', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='Публікації', to='news_fr.category_fr', verbose_name='Категорія')),
                ('tags_fr', models.ManyToManyField(blank=True, related_name='Публікації', to='news_fr.tag_fr', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Публікація(ю)',
                'verbose_name_plural': 'Публікації',
                'ordering': ['-created_at_fr'],
            },
        ),
    ]
