# Generated by Django 4.0.3 on 2022-03-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_post_options_post_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('author', models.CharField(blank=True, max_length=150, verbose_name='Автор')),
                ('content', models.TextField(blank=True, verbose_name='Вміст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено коли')),
            ],
            options={
                'verbose_name': 'Форма(у) контакту',
                'verbose_name_plural': 'Форми контакту',
                'ordering': ['-created_at'],
            },
        ),
    ]
