# Generated by Django 4.0.3 on 2022-03-30 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва категорії')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категорія(ю)',
                'verbose_name_plural': 'Категорії',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('author', models.CharField(blank=True, max_length=150, verbose_name='Автор')),
                ('content', models.TextField(blank=True, verbose_name='Вміст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено коли')),
            ],
            options={
                'verbose_name': 'Форма(у) контакту',
                'verbose_name_plural': 'Форми контакту',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва тєгу')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Тег(у)',
                'verbose_name_plural': 'Теги',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок публікації')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('author', models.CharField(blank=True, max_length=150, verbose_name='Автор')),
                ('content', models.TextField(blank=True, verbose_name='Вміст')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено коли')),
                ('published', models.BooleanField(default=True, verbose_name='Опублікувати')),
                ('views', models.IntegerField(default=0, verbose_name='Кількість переглядів')),
                ('short_story', models.BooleanField(default=False, verbose_name='Коротка новина')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='Публікації', to='news_en.category', verbose_name='Категорія')),
                ('tags', models.ManyToManyField(blank=True, related_name='Публікації', to='news_en.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Публікація(ю)',
                'verbose_name_plural': 'Публікації',
                'ordering': ['-created_at'],
            },
        ),
    ]
